# Generated by Django 5.2.6 on 2025-09-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('football_shirt', 'Football Shirt'), ('football_shoe', 'Football Shoe'), ('football_hat', 'Football Hat'), ('football_accessories', 'Football Accessories')], default='update', max_length=20),
        ),
    ]
