# Generated by Django 5.2.6 on 2025-10-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('football_shirt', 'Football Shirt'), ('football_shoe', 'Football Shoe'), ('football_hat', 'Football Hat'), ('football_accessories', 'Football Accessories')], default='football_shirt', max_length=30),
        ),
    ]
